### ISSUE TITLE
[PE-D][Tester E] UG Bug - Add New Person

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T13-3/tp#156]
Under add new person, the first example didn't provide the `s/` prefix which hindered me a little bit in my typing

Might need to explain what status is too because it's a vague term.

Might also want to show example usage of `l/` because I didn't know I needed to put the https:// in front

![image.png](https://raw.githubusercontent.com/rylzxc/ped/main/files/441da351-e227-44d2-ac3b-b5a98ff8b00d.png)

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: rylzxc/ped#1

**Comment by pratham31012002** [comment]
Update UG.
