### ISSUE TITLE
[PE-D][Tester E] Person not in app after startup

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T13-3/tp#170]
Added a person into the app, exited and then re opened the app, but doesnt reflect the added person in app. It is in the .json file though.

Tried to edit the .json file but to no avail as well.

Performing `clear`, exiting and re opening the app just repopulates with sample data.

![image.png](https://raw.githubusercontent.com/rylzxc/ped/main/files/4dd35732-2ccc-4094-91be-d23a24127ba4.png)

This also violates the features below.

![image.png](https://raw.githubusercontent.com/rylzxc/ped/main/files/68be0a73-f301-46a0-98a4-ecf0cc760af3.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: rylzxc/ped#4

**Comment by pratham31012002** [comment]
To be fixed.
